$ = window.jQuery;
var tagsArray = [
  '3D Printing',
  'Accounting',
  'Aerospace & Defense',
  'Agriculture',
  'Airlines',
  'Alternative Medicine',
  'Animation',
  'Apparel & Fashion',
  'Apparel & Footwear',
  'Architecture',
  'Arts',
  'Arts & Crafts',
  'Asset Management',
  'Audio',
  'Automation',
  'Automotive',
  'Banking & Mortgages',
  'Beverages',
  'Biotechnology',
  'Broadband',
  'Broadcasting',
  'Building Materials',
  'Business Supplies',
  'Chemicals',
  'Civil Engineering',
  'Cloud Services',
  'Communications',
  'Computer Hardware',
  'Computer Networking',
  'Construction',
  'Consulting & Professional Services',
  'Consumer Discretionary',
  'Consumer Electronics',
  'Consumer Staples',
  'Corporate & Business',
  'Cosmetics',
  'Design',
  'E-Commerce & Marketplaces',
  'E-Learning',
  'Education',
  'Electrical',
  'Energy',
  'Entertainment & Recreation',
  'Eyewear',
  'Facilities',
  'Family Services',
  'Finance',
  'Financial Services',
  'Fine Art',
  'Fishery',
  'Food',
  'Food Production',
  'Food, Beverage & Tobacco',
  'Fundraising',
  'Gambling & Casinos',
  'Graphic Design',
  'Ground Transportation',
  'Health & Wellness',
  'Health Care',
  'Higher Education',
  'Home & Furniture',
  'Home Improvement',
  'Human Resources',
  'Import & Export',
  'Industrials & Manufacturing',
  'Information Technology & Services',
  'Insurance',
  'International Relations',
  'International Trade',
  'Internet',
  'Investment',
  'Investment Banking',
  'Investment Management',
  'Jewelry, Watches & Luxury Goods',
  'Legal Services',
  'Libraries',
  'Machinery',
  'Maritime',
  'Market Research',
  'Marketing & Advertising',
  'Mechanical Engineering',
  'Media',
  'Medicine',
  'Military',
  'Mining & Metals',
  'Mobile',
  'Movies & TV',
  'Museums',
  'Music',
  'Nanotechnology',
  'Oil & Gas',
  'Outsourcing',
  'Packaging & Containers',
  'Paper Goods',
  'Payments',
  'Pharmaceuticals',
  'Pharmacy',
  'Photography',
  'Plastics',
  'Plumbing',
  'Pornography',
  'Primary & Secondary Education',
  'Printing',
  'Public Relations',
  'Publishing',
  'Ranching',
  'Real Estate',
  'Renewable Energy',
  'Renewables & Environment',
  'Research',
  'Restaurants',
  'Security',
  'Services',
  'Shipbuilding',
  'Shipping & Logistics',
  'Sporting Goods',
  'Sports & Fitness',
  'Supermarkets',
  'Talent Agencies',
  'Technology',
  'Telecommunications',
  'Textiles',
  'Tobacco',
  'Tools',
  'Translation',
  'Transportation',
  'Travel & Leisure',
  'Utilities',
  'Venture Capital',
  'Veterinary',
  'Video Games',
  'Wholesale',
  'Wireless ',
  'B2B',
  'B2C',
  'E-Commerce',
  'Enterprise',
  'ISP',
  'Marketplace',
  'Mobile',
  'SAAS'
]

var selected = new Array();

function makeSnippet(selected){
  return 'window.reveal && '+JSON.stringify(selected)+'.some(function(tag){return (window.reveal.company.tags).indexOf(tag)>-1})';
}

function addListeners(){
  $("#myForm").on("change", ":input", function() {
    selected = []; //rather than adding/removing elements we just clear the array and find 'em all
    $("input:checked").each(function(box) {
      selected.push($(this).val());
    });
    $("#results").html(makeSnippet(selected))
  });
}
$( document ).ready(function() {
  var bigCheckboxList = tagsArray.map(function(tag){
    return '<input type="checkbox" name="'+tag+'" value="'+tag+'">'+tag+'<br>'
  }).join('\n');
  $("#myForm").append(bigCheckboxList);
  addListeners();
});
